default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: swc_development

test:
  <<: *default
  database: swc_test

production:
  <<: *default
  database: swc_production
  username: swc
  password: <%= ENV['SWC_DATABASE_PASSWORD'] %>

remote_db: &remote_default
  adapter:  <%= ENV['DATABASE_ADAPTER'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  host:     <%= ENV['DATABASE_HOST'] %>
  timeout:  <%= ENV['DATABASE_TIMEOUT'] %>

# remote_db_test:
#   adapter:  <%= ENV['DATABASE_ADAPTER'] %>
#   host:     <%= ENV['DATABASE_HOST'] %>

# remote_db_development:
#   <<: *remote_default
